name: CI Back-end
on:  
push:
  branches:
    - 'main'
jobs:
  primeiro-job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribuition: 'temurin'
        - name: Maven Compile/Test
          worling-directory: sgcmapi/
          run: mvn compile test